### ISSUE TITLE
After whitelableing none of Mautic features works even buttons

### ISSUE THREAD

**Issue by Abdelrhman161** [nickian/mautic-whitelabeler#162]
**Describe the bug**
After whitelableing mautic everything stop working  buttons, menus, statistics, etc.

**Mautic Version**
MAUTIC V5.0.4

**Web Server Error Logs**
I can't access log tab in sysinfo page

**Hosting Environtment**
Ubuntu 22.04, Docker V26.1.3,  container image mautic/mautic:v5.0.4:apache

**Screenshots**
![Screenshot_٢٠٢٤-٠٥-١٩-١٤-٢٠-٤٦-٧٧٧-edit_com android chrome](https://github.com/nickian/mautic-whitelabeler/assets/105675263/2eb4a67f-d714-4514-9f42-6392a0765d61)

**Comment by Abdelrhman161** [comment]
I have got some error log

**Current Error Log**
```
[2024-05-19T13:16:53.895597+00:00] mautic.WARNING: PHP Warning - Undefined array key "path" - in file /var/www/html/docroot/app/bundles/CoreBundle/Controller/ExceptionController.php - at line 106 [] {"hostname":"4e2348bf89e8","pid":24}
[2024-05-19T13:21:08.365972+00:00] mautic.WARNING: PHP Warning - Undefined array key "path" - in file /var/www/html/docroot/app/bundles/CoreBundle/Controller/ExceptionController.php - at line 106 [] {"hostname":"4e2348bf89e8","pid":23}
```

**Comment by nickian** [comment]
I'm not really familiar with how the Docker version of Mautic works. Can you share how you installed it? Do you have a `docker-compose.yml` file? That looks like an unrelated PHP warning to me. Something else is going on. Have you made sure your webserver has the correct permissions on the Mautic folder after whitelabeling?

**Comment by Abdelrhman161** [comment]
**docker-compose.yml**

```
version: "3.9"

services:
  database:
    image: mariadb:latest
    container_name: mautic-db
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: mautic
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    container_name: mautic
    image: mautic/mautic:5.0.4-apache
    volumes:
      - mautic_data:/var/www/html:rw
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=your-password
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_TABLE_PREFIX=mautic
    restart: always
    depends_on:
      - database
    links:
      - database
    networks:
      - mauticnet
    ports:
      - "8888:80"

networks:
  mauticnet:

volumes:
  database:
  mautic_data:
```
